version: "3.4"
x-app: &default-pedis
  image: ko.local/ppathe/pedis/pedis-9e6a4042beefc3cd7105eec240e5b3ab:c3cb180cc2aba05bc6202089b4d76c334f18c7a2a5fdf9e2f53691d1bfcce727
  healthcheck:
    test: /ko-app/pedis --health
    interval: 1s
    retries: 5
    start_period: 1s
    timeout: 10s
services:
  pedis-a:
    <<: *default-pedis
    container_name: pedis-a
    entrypoint: /ko-app/pedis --cluster http://pedis-a:12379
    ports:
      - "6379:6379"
  pedis-b:
    <<: *default-pedis
    container_name: pedis-b
    entrypoint: /ko-app/pedis --id 2 --join --cluster http://pedis-a:12379,http://pedis-b:12379
    depends_on:
      - pedis-a
  pedis-c:
    <<: *default-pedis
    container_name: pedis-c
    entrypoint: /ko-app/pedis --id 3 --join --cluster http://pedis-a:12379,http://pedis-b:12379,http://pedis-c:12379
    depends_on:
      - pedis-a
